nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
        - "80:80"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock
        - ./nginx/proxy.conf:/etc/nginx/conf.d/my_proxy.conf

jira:
    image: cptactionhank/atlassian-jira-software
    ports:
        - "8080:8080"
    environment:
        - VIRTUAL_HOST=jira.smarthome.dev
        - CATALINA_OPTS=-Datlassian.plugins.enable.wait=300
    links:
        - db:jira-db.smarthome.dev
    volumes:
        - ./jira:/var/atlassian/jira

db:
    image: mysql:5.6
    ports:
        - "3306:3306"
    environment:
        - VIRTUAL_HOST=jira-db.smarthome.dev
        - MYSQL_ROOT_PASSWORD=root
    volumes:
        - ./data:/var/lib/mysql
        - ./tmp:/tmp/dumps
