jira:
    image: cptactionhank/atlassian-jira-software
    container_name: jira_service
    ports:
        - "8080:8080"
    environment:
        - CATALINA_OPTS=-Datlassian.plugins.enable.wait=300
    links:
        - db
    volumes:
        - ./jira:/var/atlassian/jira

db:
    image: postgres:9.5
    container_name: jira_db
    environment:
        - POSTGRES_DB=jira
        - POSTGRES_USER=jira
        - POSTGRES_PASSWORD=jira
    volumes:
        - ./postgresql/data:/var/lib/postgresql/data
        - ./tmp:/tmp/dumps
